import numpy as np
import json
import argparse
import os
import gc
import sys
#Multipurpose cleanup script, for combining files from multiple jobs into a single file
#Currently works with the params files generated by generate_configs, and the data files from asyncSNR 

parser = argparse.ArgumentParser()
parser.add_argument('--projectdir', type=str, default=None)
parser.add_argument('--njobs', type=int, default=None)
parser.add_argument('--filetype', type=str, default="params")
args = parser.parse_args()
project_dir = args.projectdir
n_jobs = args.njobs
file_type = args.filetype

config_file = os.path.join(project_dir, "args.json")

with open(config_file) as f:
	config = json.load(f)

	#project_dir = config['project_dir']
	#n_signal_samples = config['n_signal_samples']

if file_type == "params":
	filename = ["params"]
elif file_type == "data":
	filename = ["SNR", "SNR_abs", "strain", "spectrogram", "spectrogram_re", "spectrogram_im", "spectrogram_q", "spectrogram_vitmap", "spectrogram_lineaware"]
else:
	raise ValueError("filetype must be 'params' or 'data'")


#need to load in this order to ensure samples remain saved as signals first, then noise

if file_type == "params":
	x = np.load(os.path.join(project_dir, "params_0.npy"), allow_pickle=True).item()
	z = {}

	def get_signal_end(injection_array):
		#find where the last signal sample is in the file. 
		#This ensures that files with unequal numbers of samples are handled correctly.
		indices = np.where(np.diff(injection_array))[0]
		if indices.size > 0:
			return indices[0] + 1
		else:
			return len(injection_array)

	end = get_signal_end(x['injection'])
	#print("end", end)

	for key in x.keys():
		z[key] = x[key][:end]

	for i in range(1, n_jobs):
		try:
			y = np.load(os.path.join(project_dir, "params_" + str(i) + ".npy"), allow_pickle=True).item()
		except:
			print("Could not load params_" + str(i) + ".npy")
			continue
		end = get_signal_end(y['injection'])
		print("end", end)
		for key in x.keys():
			z[key] = np.concatenate((z[key], y[key][:end]), axis=0)


	if get_signal_end(x['injection']) != len(x['injection']):
		end = get_signal_end(x['injection'])
		for key in x.keys():
			z[key] = np.concatenate((z[key], x[key][end:]), axis=0)

		for i in range(1, n_jobs):
			try:
				y = np.load(os.path.join(project_dir, "params_" + str(i) + ".npy"), allow_pickle=True).item()
			except:
				print("Could not load params_" + str(i) + ".npy")
				continue
			end = get_signal_end(y['injection'])
			print("end", end)
			for key in x.keys():
				z[key] = np.concatenate((z[key], y[key][end:]), axis=0)

	#now save the new dictionary

	np.save(os.path.join(project_dir, "params.npy"), z)
	print("Saved new params.npy")

else:
	rerun_jobs = set()
	for name in filename:
		#load the files into memory
		if os.path.exists(os.path.join(project_dir, name + "_0.npy")):
			print(f"Processing {name}")
			x = np.load(os.path.join(project_dir, name + "_0.npy"))
			#check if there are any issues with the file. Sometimes files generate with extremely large or small SNRs
			bad_samples = np.where((np.any(np.max(np.abs(x), axis = -1) < 1, axis = 0)) | (np.any(np.max(np.abs(x), axis = -1) > 1e6, axis = 0)))[0]
			if len(bad_samples) > 0:
				print(f"Warning: {name}_0.npy contains bad samples here: {bad_samples}.")
				rerun_jobs.add(0)
			for i in range(1, n_jobs):
				try:
					y = np.load(os.path.join(project_dir, name + "_" + str(i) + ".npy"))
					bad_samples = np.where((np.any(np.max(np.abs(y), axis = -1) < 1, axis = 0)) | (np.any(np.max(np.abs(y), axis = -1) > 1e6, axis = 0)))[0]
					if len(bad_samples) > 0:
						print(f"Warning: {name}_" + str(i) + ".npy contains " + str(len(bad_samples)) + " bad samples")
						rerun_jobs.add(i)
					#concatenate with a copy of y
					x = np.concatenate((x, y.copy()), axis = 1)
					#x = np.concatenate((x, y), axis=1)
					print(f"Added {name}_" + str(i) + ".npy")
					#need to free up memory
					del y
					gc.collect()
				except:
					print(f"Could not load {name}_" + str(i) + ".npy")
					exit()
			np.save(os.path.join(project_dir, name + ".npy"), x)
			print(f"Saved new {name}.npy")
			if len(rerun_jobs) > 0:
				print("One or more jobs has issues with its SNR samples! Rerunning the jobs usually fixes this.")
				job_ids = ",".join([str(job_id) for job_id in rerun_jobs])
				jobname = "SNR_" + config['jobname']
				cleanup_jobname = "SNR_cleanup_" + config['jobname']
				SNR_mem = config['SNR_mem']
				savedir = config['project_dir']
				rerun_script = """SNR_job=$(sbatch --job-name={} --array={} --mem={}G --parsable ${{GWSAMPLEGEN_DIR}}/share/SNR_np.sh {} {})""".format(jobname, job_ids, SNR_mem, config_file, n_jobs)
				rerun_cleanup = """final=$(sbatch --job-name={} --mem=180G --ntasks=2 --dependency=afterok:$SNR_job --output=${{GWSAMPLEGEN_DIR}}/logs/%x.log  --parsable ${{GWSAMPLEGEN_DIR}}/share/cleanup.sh {} {} "data")""".format(cleanup_jobname, savedir, n_jobs)
				print("To rerun the jobs, run the following commands:")
				print(rerun_script)
				print(rerun_cleanup)
				sys.exit(1)
			else:
				#now remove the old files
				for i in range(n_jobs):
					try:
						os.remove(os.path.join(project_dir, name + "_" + str(i) + ".npy"))
					except:
						print(f"Could not remove {name}_" + str(i) + ".npy")
						exit()
				print("removed temporary files")
				#check if there's any zeros in the file
				if np.any(x == 0):
					print(f"Warning: {name}.npy contains zeros")
